### ISSUE TITLE
Blind parameters should allow free definition of values

### ISSUE THREAD

**Issue by M0ebiu5** [alisdairjsmyth/node-red-contrib-blindcontroller#11]
Hi,
i have slat blinds and in my case 0 represents blind completely closed and 100 completely open.
The min. step width to change the angle of the slats is 0.005. 

With them, there are 2 possibilities to control the sunlight:
1. Open and close the blind to a certain position
2. Only change the angle of the slats. (6 different angles possible)

Now, it would be nice, if the node would let me enter "free" values for the blind parameters, so that i could use both options with my hardware (homematic HM-LC-Bl1PBU-FM).
Thanks!

**Comment by alisdairjsmyth** [comment]
At this stage, this project only has the capability to calculate the vertical position of the blind as a way of controlling the extent to which sunlight enters the room.  It doesn't have any capability with regard to controlling the angle of slats - though that could be an interesting extension.

As to your request, what do you mean as "free" values?  I gather you are thinking this could be a mechanism by which both the vertical position and angle of slats could be controlled.

As to whether 0 represents fully open or closed, I could include a parameter to allow selection.  Alternatively this could be handled within the Node-RED flow through the use of a function node.

**Comment by M0ebiu5** [comment]
About "free" values: 
Currently it is not possible to turn around the min / max settings. Impossible to set maximum closed position to "0". Also the max/min and increment is not allowed to be float. 
I dont think there is an additional parameter needed - the calculation should be able to use any range and step size and project the "sunlight" function on to the given range.

Controlling the slats should be easy, cause it works with the same parameters. If i could enter 0 for max, 0.03 for min and 0.005 as step size, your blindcontroller node would already only adjust the angle of the slats - and after playing with the other parameters, maybe the output is good enough.

**Comment by alisdairjsmyth** [comment]
The degree to which the window is covered is expressed as an integer representing a percentage - hence 0 to 100, where 0 is fully open and 100 is fully closed.  As such the increments are also integers.  This model is consistent with Apple HomeKit specification for Window services, and Z-Wave standard for Window Coverings.  Within the configuration, the following parameters are percentages expressed as percentages:
- Increment
- Maximum Open Position
- Maximum Closed Closed
- Night Position

As your requirement is for 100 to be fully open and 0 to be fully closed, you could use a function node in your Node-RED flow to switch the value of ``msg.payload.blindPosition``.  The function would be:
```
msg.payload.blindPosition = 100 - msg.payload.blindPosition
return msg
```

Here is a sample Node-RED flow containing this function - [sampleFunction.txt](https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller/files/874953/sampleFunction.txt) - it can be imported into Node-RED from within the console.

With regard to the slats, you could configure the Blind Controller node with an increment of 20 ((0.005/0.3)*100) and use default max and min.  If you need a multiple of 0.005 to control the device themselves, you could once again use a function node to convert to the required value.

```
msg.payload.blindPosition = ((100 - msg.payload.blindPosition) / 20) * 0.005
return msg
```

... and sample flow - [sampleSlatFunction.txt](https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller/files/874997/sampleSlatFunction.txt)

Hope this helps.  Let me know how you go.

**Comment by M0ebiu5** [comment]
Didn't know that these configuration values are percentages (most settings are missing the unit in the readme). I will try it with the function node.
Thanks for your help!

**Comment by alisdairjsmyth** [comment]
No problem.  I will have another look at the documentation ([README.md](https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller/blob/master/README.md) and [node help](https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller/blob/master/blindcontroller/blindcontroller.html)) and try to make this clearer.

**Comment by M0ebiu5** [comment]
Just wanted to thank you for the nodes. It's working pretty well. Additionally to the remapping of the values, i've also added a morning and evening position (depending on sun altitude).
