### ISSUE TITLE
Explanation of orientation and offset

### ISSUE THREAD

**Issue by vzorglub** [alisdairjsmyth/node-red-contrib-blindcontroller#13]
Hello,
The documentation is a bit vague regarding the use of the orientation and offset.
Is the orientation the bearing of perpendicular of the window to geographical north?
Or is it the bearing of the wall/window to geographical north?
Could you update the drawing on the readme with the relative angles and add the North or a reference?
I believe that the offset are to due with the depth of the window through the wall, I am right?
Thank you
Vincent

**Comment by alisdairjsmyth** [comment]
The orientation is the bearing perpendicular of the window to geographical north.

The offsets were created to allow for scenarios where there is an obstacle around a window that inhibits direct sunlight.  The obstacle could be a deeply inset window, a tree, a wall, anything.

**Comment by vzorglub** [comment]
Thank you
I think the diagram is showing the offsets the wrong way around...
Quick question. Is there a way to change the mode from Winter to Summer by injecting a message?
I would like to change the mode automatically by schedule and not by editing the nodes.
Thanks

**Comment by HubertusH** [comment]
Is it possible to open the issue?
I have a wall in front of the window and the sun can shine left and right from the wall into the window. How i have to set the offset in this case - or i have to use two blindcontrollers?
Many thanks for help
Hubertus

**Comment by alisdairjsmyth** [comment]
The offset was to support cases where there is an obstacle to the right or left - rather than a scenario where the obstacle is in the middle.  This would be a new feature.

![image](https://user-images.githubusercontent.com/11627564/84025542-1e4e6500-a9cf-11ea-8d4c-2f7891692ad8.png)

**Comment by HubertusH** [comment]
Thank you for the reply!
So i wait for the new feature ;-)
Have a nice day
