### ISSUE TITLE
Orientation and Mode change

### ISSUE THREAD

**Issue by vzorglub** [alisdairjsmyth/node-red-contrib-blindcontroller#14]
Thank you
I think the diagram is showing the offsets the wrong way around...
Quick question. Is there a way to change the mode from Winter to Summer by injecting a message?
I would like to change the mode automatically by schedule and not by editing the nodes.
Thanks

**Comment by alisdairjsmyth** [comment]
I like the idea of being able switch modes without needing to edit the node and restart the flow.  This is presently possible using the **Multi Blind Controller** with the **blind** message, however I think will add support for a **mode** message which triggers a switch of mode.

**Comment by vzorglub** [comment]
Another idea, maybe is to be able to change the offsets by message.
For example, in front of one of my windows is a house across the street.
In winter (As of now) I have to use two blind controllers for this window as the sun is lower than the house to create a gap in the sun exposure. But on or around the 14th February the sun should be above the house and therefore I will not need two blind controllers any,more.
Or we could have a "profile" with points such as: { point1: {orientation: -180, azimuth: 5}, point2: {orientation:-140, azimuth: 5}, point3: {orientation: -140, azimuth: 15}...... Thereby creating a simple vue of the horizon relative to the windows. When the sun is over the line of the horizon we have sun exposure!! I don't know how difficult this would be to implement. Just an idea...
Regards

**Comment by vzorglub** [comment]
[SunController.txt](https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller/files/1585733/SunController.txt)

**Comment by vzorglub** [comment]
Hello,
I have had a go.
Newbie at javascript
and never coded for node-red so I don't really understand the config part yet.
I should need a new config to add the "profiles"
I added the "mode" message. Please tell my if thats right.
And the profile too.
the profile should be an array of objects starting from {azimuth: 0, altitude:x} to {azimuth:180, altitude: y}. I guess the default could be {azimuth: 0, altitude:0} to {azimuth:180, altitude: 0}.
I am also using a node called node-red-contrib-ramp-thermostat that uses configurations nodes to define profiles for heating. This is kind of what I had in mind. This way the blind controller could take into accounts obstables such as buildings, mountains....
Please let me know.

I haven't tested any of this code, I just had a go...

Thanks
Vincent

**Comment by alisdairjsmyth** [comment]
Sorry for the delayed response ... Christmas and New Years etc.

I have had a look at your suggestion.  I like the idea that you submit a single **mode** message and it updates the mode for all blinds - though I might go about implementing it differently.

As to the profile idea, there is an existing mechanism call **altitude threshold**.  I think it might do what you want.  This mechanism allows for obstacles that block direct sunlight until certain azimuths - in my case a fence line.  Until the sun reaches a certain azimuth the fence line blocks direct sunlight entering through certain windows.

**Comment by alisdairjsmyth** [comment]
Support for mode message available in npm v4.4.0.
