### ISSUE TITLE
Cloud payload

### ISSUE THREAD

**Issue by myozone** [alisdairjsmyth/node-red-contrib-blindcontroller#15]
It might be better to us msg.data.currently.cloudCover rather than msg.payload.clouds or have a choice, for me it tracks the actual weather better.

**Comment by alisdairjsmyth** [comment]
I have tried to avoid coupling this node to a specific weather node - though it is heavily influenced by the output of the [darksky node](https://www.npmjs.com/package/node-red-node-darksky).

The blindcontroller uses two properties `maxtemp` and `clouds` from `msg.payload`.  If you wanted to use the `msg.data.currently.cloudCover` from the darksky node as the `clouds` value, you could use a `function` or `template` or `change` node to replace the `msg.payload.clouds` value in your flow.

<img width="698" alt="flow" src="https://user-images.githubusercontent.com/11627564/38530566-8fc884b2-3cae-11e8-83ef-5bd553ca23cd.PNG">

`msg.payload = {
    clouds: msg.data.currently.cloudCover
};
return msg;`
