### ISSUE TITLE
Altitude Treshold is ignored

### ISSUE THREAD

**Issue by Glatzi77** [alisdairjsmyth/node-red-contrib-blindcontroller#16]
Thx for this really fantastic node!
I've got the situation that the altitude treshold is not used for calculation:

My sunpos object gives the following data:

`{"_msgid":"1b845056.26a1a","topic":"sun","payload":{"startTime":1532144679758,"endTime":1532201950777,"sunInSky":true,"altitude":24.87895830143003,"azimuth":87.70194242517096,"altitudeRadians":0.43421973682632986,"azimuthRadians":-1.6109049978760595},"location":{"lat":"51.204468","lon":"6.396424"},"time":1532155174235,"sunTimes":{"solarNoon":1532173315267,"nadir":1532130115267,"sunrise":1532144679758,"sunset":1532201950777,"sunriseEnd":1532144928462,"sunsetStart":1532201702073,"dawn":1532142112616,"dusk":1532204517918,"nauticalDawn":1532138516875,"nauticalDusk":1532208113660,"nightEnd":1532131924872,"night":1532214705663,"goldenHourEnd":1532147716272,"goldenHour":1532198914263}}
`

The payload for the blind is defined as follows:

`{"channel":"1","mode":"Summer","orientation":30,"noffset":90,"poffset":90,"top":240,"bottom":30,"depth":100,"altitudethreshold":30,"increment":1,"maxopen":1,"maxclosed":100,"temperaturethreshold":"","cloudsthreshold":"0.8","nightposition":0,"expiryperiod":2,"blindPosition":93,"sunInWindow":true,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","weather":{}}`

The blind is shutdown because of blindPositionReasonCode 05.
From my understanding the blindposition should not be calculated because of the Altitude Treshold parameter?

I've found that piece of code below 

` else if (
                 blind.altitudethreshold &&
                  sunPosition.altitude < blind.altitudethreshold
                ) {
                  blind.blindPositionReasonCode = "03";
                  blind.blindPositionReasonDesc = RED._(
                    "blindcontroller.positionReason.03"
                  );
          }`

I've checked the code and it seems that this statement is perhaps the problem? In my opinion this piece of code is never called because the thresholds for ignoring the calculation must be called at first in  **function calcBlindPosition** below line 524 (blindcontroller.positionReason.07) so that it gets checked at first & now looks like this:

`
if (isTemperatureAConcern) {
          blind.blindPosition = blind.maxclosed;
          blind.blindPositionReasonCode = "07";
          blind.blindPositionReasonDesc = RED._(
            "blindcontroller.positionReason.07"
          );
        }
        else if (
                  sunPosition.altitude < blind.altitudethreshold
                ) {
                  blind.blindPositionReasonCode = "03";
                  blind.blindPositionReasonDesc = RED._(
                    "blindcontroller.positionReason.03"
                  );
          }
          else {
          blind.sunInWindow = isSunInWindow(blind, sunPosition.azimuth);
`

What is the reason for comparing 

**blind.altitudethreshold &&
                  sunPosition.altitude < blind.altitudethreshold**

This statement will never be true because of comparing the same value twice? Would be glad to here from you.

**Comment by alisdairjsmyth** [comment]
I will have a look.  The `altitude threshold` is intended handle situation where the sun doesn't enter the window until it reaches a particular altitude in the sky.  At first glance, the blinds shouldn't be adjusted because altitude of the sun less than the threshold.

With regards the condition `blind.altitudethreshold && sunPosition.altitude < blind.altitudethreshold`, it is first testing whether a threshold has been set (proceeding the `&&`) and then the comparison of values.

**Comment by alisdairjsmyth** [comment]
Fix available in npm version 4.4.2
