### ISSUE TITLE
Units not defined in the Flow description

### ISSUE THREAD

**Issue by ouinouin** [alisdairjsmyth/node-red-contrib-blindcontroller#18]
Hi, 
I m trying to use your nodered flow, for the moment stille experimenting, but it would be great to have an idea of the units to be used while configuring all parameters (mm , meters, cm ?).

Regards.

**Comment by alisdairjsmyth** [comment]
It is actually unit of measure agnostic, you just need to specify all the length parameters in same unit of measure.  I personally use centimetres.

**Comment by renne** [comment]
@alisdairjsmyth 
This has also been asked in #12.
Please add information about agnostic units in [README.md](https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller/blob/master/README.md).
