### ISSUE TITLE
Temperature / Clouds Threshold position improvements

### ISSUE THREAD

**Issue by jonferreira** [alisdairjsmyth/node-red-contrib-blindcontroller#19]
Hi,

I'm wondering if you'd be interested in adding a Temperature / Clouds Threshold **position** variable.
Currently if Temperature Threshold is met blind will move to Max Closed position. Ideally I'd like to have a Temperature / Clouds Threshold **position** variable where (pseudo code)

If Current Temp > Temperature Threshold then position = Temperature Threshold Position || Max Closed position

The idea is under **normal** circumstances I'd like my blinds to be at least 50% opened (Max Closed Position) but if ambient temperature > 40c for example and sun is in window then close to say 90% - makes sense?

If interested I can do a pull request

**Comment by alisdairjsmyth** [comment]
Sounds like a useful feature.  I would be happy to accept such a pull request.  In its implementation, may I suggest two separate position parameters: one for temperature; and one for clouds.

**Comment by jonferreira** [comment]
https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller/pull/20

**Comment by alisdairjsmyth** [comment]
Incorporated into v4.5.0
