### ISSUE TITLE
winter blinds controller

### ISSUE THREAD

**Issue by tzapu** [alisdairjsmyth/node-red-contrib-blindcontroller#2]
Hello,
This is such a cool thing, i really really want to get to integrate it with my blinds, but i need to make a way of controlling them first.

Anyway, not a bug, but exploring if there is any possibility of extending this for winter use, when I would prefer for instance to open the blinds to gain maximum advantage from the sun on sunny days. 

Will this work for blinds that would only do open/close? with no intermediary position?
Thank you

**Comment by alisdairjsmyth** [comment]
I have to admit this node was developed with a view of constraining rather than maximising the amount of direct light entering the room.  That said, the **depth** property could be set to a value appropriate with that goal ie a large value.

Yes, this node could support blinds that only open/close by setting the **increment** property to 100.

**Comment by jonferreira** [comment]
I'm actually trying to do the same thing. My take is blindPosition returns a "closed" value percentage to prevent sunlight to get inside - lets call it "cooling mode".
If one wants to maximise the light entering the room then the inverse logic should work fine, i.e. 100 - blindPosition - am I right?

**Comment by alisdairjsmyth** [comment]
As I mentioned in the previous comment, this node was developed with a view of constraining the amount of direct light entering the room.  This model came about when I asked my wife why she was setting the blinds the positions she was:
- To protect our lounge (and other furniture) from extreme UV and therefore fading;
- To keep extreme heat out

It was the first of these reasons that resulted in me considering sun position as the basis of calculating the appropriate blind position.

Maximising light entering the room is almost irrelevant of the sun position - and more tied to the sun times. i.e. At sunrise open the blinds and at sunset close them.  Please comment if you view it differently.

I will think about this request a little more - maybe I could include a "mode" configuration to support such choice between "constraining" and "maximising" ...

**Comment by jonferreira** [comment]
That would be great without a question :-)
What I'm doing now is monitoring inside and outside temperature and "weather condition" (cloudy,sunny, etc) and decide if I want to heat or cool the room. 
this is mainly used during the winter when it could be "cold" outside but the sun light is actually enough to heat the room and save a few € on the gas bill.
Again, unless I'm missing something, this is easily done by the end user as-is by simple setting 100 - blindPosition.
What I would actually love to see implemented was a maximum and minimum position variable. For some reason I may want to never get a fully closed roller blind during the day so I can still have some day light getting in - makes sense?

**Comment by alisdairjsmyth** [comment]
@tzapu and @jonferreira - I am considering your request, and was thinking of implementing it as described below.  Is this in line with what you were thinking?

New Configuration:
- **Mode**: Two settings, "Summer" and "Winter".  In "Summer" mode, the blinds are controlled to constrain the amount of direct light allowed to enter the room.  In "Winter" mode, the blinds are controlled to maximise the amount of direct light allowed to enter the room.
- **Max Open**: The maximum extent to which the blind can be opened during daylight hours.  Defaults to 0.
- **Max Closed**: The maximum extent to which the blind can be closed during daylight hours.  Defaults to 100.

In Summer Mode, the existing behaviour would be augmented to take into account the **Max Open** and **Max Closed** configuration settings.

In Winter Mode, while the sun is in the window (using current determination) the blind position will be set to **Max Open**.  However when the sun is not in the window, the blind position will be set to **Max Closed**.

**Comment by tzapu** [comment]
nice, that would be very very nice :D
my blinds can be only open and closed, no intermediary position, so can t comment on max open/max closed. i also can t read back position.
the only thing i am thinking is interoperation with weather, if it s winter, and it s cloudy/rainy/snowy ... jsut anything that is dark, i d rather not have the blinds open... of course, these conditions could change during the day, so half of day bad weather and half sunny, it would be ideal if it would take into account when weather changes...
anyway, anything is better than nothing, the above is just me open eyed dreaming :D
thanks for taking this into consideration

**Comment by jonferreira** [comment]
sounds great @alisdairjsmyth, that seems to cover all we've been talking :-)

@tzapu and @alisdairjsmyth - instead of a fixed "Mode" rule it would be great to be able to change this based on weather conditions, room temperature etc. I suppose the easiest way is to use an additional JS function node after the Blinds node and edit the payload

**Comment by alisdairjsmyth** [comment]
Added the basic "maximise" functionality as described above.  In addition to **mode**, **maxopen**, and **maxclosed**, I also added **nightposition**.  The last property allows configuration of the blind positions outside daylight hours.

Available via npm as v3.0.0.

**Comment by jonferreira** [comment]
fantastic work, I've just updated it and will start testing :)

**Comment by alisdairjsmyth** [comment]
You could also run it through the simulator flow I posted yesterday by changing the mode to "Winter".

**Comment by tzapu** [comment]
thank you so very much
i ll try and add and test as well for a lengthy amount of time :D

**Comment by jonferreira** [comment]
Think there may be something wrong with the Multi Blind Controller on this last version, it no longer outputs **blindPosition**

`{ "topic": "blind", "payload": { "channel": 2, "orientation": 90, "noffset": 45, "poffset": 45, "top": 250, "bottom": 50, "depth": 999, "increment": 5, "mode": "Summer", "sunInWindow": true, "blindPositionReasonCode": "05", "blindPositionReasonDesc": "Sun in window" }, "_msgid": "e77262c.f188da", "data": { "channel": 2, "altitude": 0.6817763956460959, "azimuth": 97.78310821568581 } }`

**Comment by alisdairjsmyth** [comment]
@jonferreira - what were the settings of mode, maxopen, maxclosed, and
nightposition?

**Comment by jonferreira** [comment]
@alisdairjsmyth - that was copy paste from the example node you just gave me :)

It's only on the Multi Blind Controller though, Single Blind Controller still have the same output as before...

**Comment by alisdairjsmyth** [comment]
Published bug fix to npm as v3.0.1.

**Comment by jonferreira** [comment]
great work @alisdairjsmyth 

I can confirm blindPosition is back :-)

**Comment by alisdairjsmyth** [comment]
I am going to close down this thread.  If you would like the "Winter" mode to be enriched, we can handle that through a new one.
