### ISSUE TITLE
Allow close payload of 0

### ISSUE THREAD

**Issue by Swiftnesses** [alisdairjsmyth/node-red-contrib-blindcontroller#25]
Hello,

My blinds use the opposite logic for open close, i.e. closed is 0 and open is 100.

Could you allow the node to validate max closed 100 and max open 0?

Currently I reverse the logic via a function, but with larger flows, having 2 numbers can become troublesome :(

**Comment by alisdairjsmyth** [comment]
Let me think about this.  The current recommendation would be to use a function node to "reverse the polarity" of the output.

**Comment by alisdairjsmyth** [comment]
Available in v4.7.0 via npm

**Comment by Swiftnesses** [comment]
Thanks @alisdairjsmyth
