### ISSUE TITLE
Increment and summer mode, does it actually do anything?

### ISSUE THREAD

**Issue by Swiftnesses** [alisdairjsmyth/node-red-contrib-blindcontroller#26]
Hi,

Firstly, thanks for saving my furniture from UV rays!

I'm wondering if I can implement the nodes in a way to get a gradual movement of the blind(s) as the sun rises and sets. My blinds are cable of 1% increments but currently it only seems to use either fully open or fully closed - I've read this is the intended behaviour, in which case, what is increment actually for?

I was hoping the blind(s) would lower / raise based on the suns position and inputted parameters...

**Comment by alisdairjsmyth** [comment]
It should support the gradual movement you are looking for.  The fidelity of the movement is determined by the increment.  Mine only support 25% increments - ie 5 positions, whereas yours should be able to be positioned in any value between 0 and 100 inclusive.

If you are looking to save your furniture from UV rays - you want to restrict the amount of light entering the room and should use the "Summer" mode.  The position of the blind is driven by how far you would like direct light to enter the room.  Make sure you enter of the dimensions of the window and depth as integers of a uniform unit of measure (I use centimeters).

The "Winter" maximises the amount of direct sunlight entering the room, and as a consequence has a more open / closed mode of operation.  If the sun is in the window it will be open.
