### ISSUE TITLE
UV Threshold :-)

### ISSUE THREAD

**Issue by Swiftnesses** [alisdairjsmyth/node-red-contrib-blindcontroller#28]
Hi,

We use the controller to prevent fading to our furniture. Given the fade damage is directly correlated to the UV intensity, it would be ideal if you could add a UV threshold, i.e. if the UV is <= 2, keep the blinds up (I could also use my own UV sensors to ensure this is accurate!).

IMO, this would be a real asset to people like me who use this awesome controller to prevent fading to furniture / carpets.

Thanks in advance.

**Comment by alisdairjsmyth** [comment]
I think this is a good idea.  Let me give it some thought.

**Comment by Swiftnesses** [comment]
Thanks @alisdairjsmyth. I did a TERRIBLE workaround via my fork which *seems* to work okay (just finished it).

P.S. I'm no coder!

**Comment by alisdairjsmyth** [comment]
Incorporated into v4.8.0.  If a UV Index Threshold is specified, the position calculation is only calculated when the UV Index is below the specified threshold.

**Comment by Swiftnesses** [comment]
Awesome work, thanks @alisdairjsmyth!
