### ISSUE TITLE
Orientation problems

### ISSUE THREAD

**Issue by jonferreira** [alisdairjsmyth/node-red-contrib-blindcontroller#3]
Let me start by saying **fantastic work!**

I can't imagine how much time and effort are into this so kudos for that!

I'm having a hard time figuring out how the Orientation bit works. At first I though it would be just a "degrees field":

North = 0
East = 90
South = 180
West = 270

So I've created 4 dummy "blinds" with these orientations, 0 offsets and 999 depth.
Seemed to work for a bit but now (18pm give or take, almost sunset at West) the "South Blind" is now "moving", i.e.closing, while East and North are at 0.

I have the feeling i'm not using the Orientation field as expected.

Sun position is here: http://suncalc.net/#/39.4097,-9.1262,20/2016.03.04/18:01

node-red 
![node-red](https://cloud.githubusercontent.com/assets/7714292/13536166/532fb0fe-e236-11e5-90b6-4538ce43b627.PNG)

**Comment by alisdairjsmyth** [comment]
@jonferreira - Orientation should work exactly as you describe, it is a compass bearing, with North = 0, East = 90 etc.

The key value here are the Offset settings.  With a value of 0, the sun is considered to be in the window if sun's azimuth is +/- 90% of the window's Orientation i.e. for the South Blind between 270 (West) and 90 (East), and for West Blind between 0 (North) and 90 (South).  Given the sun is setting slightly South of West at the location, I would expect the West and South windows to be considered in the sun and have the possibility of settings greater than 0%.  Given the same sun position, I would also expect the settings for the North and East to be 0% as they are not considered to be in the sun.

The calculated blind position is however dependent upon the window dimensions (Top, Bottom) and allowed Depth - so I can check the calculations, do you mind sharing the other settings for the South and West windows?

**Comment by jonferreira** [comment]
@alisdairjsmyth thanks for answering this quick :-)

That makes sense actually :)
So if I wanted to restrict the "angle" I can set both offsets to 45º, for instance, which would give a 90º angle instead of the default 180º.

The reason why South Blind "moved" way after the West Blind (which seemed a bit odd at first) is likely due to Top/Bottom measurements. My apartment is built on a hill which makes measurements really hard to take - West side is one story up (~2 meters up give or take) while East is on the ground floor.

What I will probably do for now is to set all windows at "ground floor", i.e. Top 200 and Bottom 0, and see how it affects the overall behaviour.
Current settings are bellow: 

North
Top=400
Bottom=200
Depth=999

West
Top=400
Bottom=200
Depth=999

South
Top=200
Bottom=0
Depth=999

East
Top=200
Bottom=0
Depth=999

For now I'm gathering data logging every blind so I can later read through all that. will probably change offsets tomorrow to 45º and see how it affects behaviour after a few more days gathering data

Again, fantastic work :-)

**Comment by jonferreira** [comment]
OK so Saturday night I’ve added a Negative Offset and Positive Offset of 45º to each blind and set top to 250 and Bottom to 50 for experimentation.
While both North, East and West Blinds behaved pretty much as I would expect South still doesn’t seem to make sense IMO.
Here is the log:

```
{"sunInWindow":true,"blindPosition":95,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T07:10:24.393Z","altitude":0.6817763956460959,"azimuth":97.78310821568581}
{"sunInWindow":true,"blindPosition":80,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T07:20:24.425Z","altitude":2.5938065928245475,"azimuth":99.37692676525464}
{"sunInWindow":true,"blindPosition":65,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T07:30:24.445Z","altitude":4.497017778953673,"azimuth":100.98363597564241}
{"sunInWindow":true,"blindPosition":45,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T07:40:24.464Z","altitude":6.38986281384144,"azimuth":102.60682576693}
{"sunInWindow":true,"blindPosition":30,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T07:50:24.487Z","altitude":8.270714159259276,"azimuth":104.2501159010184}
{"sunInWindow":true,"blindPosition":15,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T08:00:24.510Z","altitude":10.137842579540207,"azimuth":105.91716345559685}
{"sunInWindow":true,"blindPosition":0,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T08:10:24.529Z","altitude":11.989432226721549,"azimuth":107.61170083651785}
{"sunInWindow":true,"blindPosition":20,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T17:40:24.878Z","altitude":9.49455132385897,"azimuth":254.8745886658086}
{"sunInWindow":true,"blindPosition":35,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T17:50:24.889Z","altitude":7.624275270852879,"azimuth":256.53603426006214}
{"sunInWindow":true,"blindPosition":50,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T18:00:24.899Z","altitude":5.741028091029635,"azimuth":258.17523461524775}
{"sunInWindow":true,"blindPosition":70,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T18:10:24.910Z","altitude":3.846500081591039,"azimuth":259.79584742653503}
{"sunInWindow":true,"blindPosition":85,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T18:20:24.922Z","altitude":1.94231961971291,"azimuth":261.401469285341}
{"sunInWindow":true,"blindPosition":100,"blindPositionReasonCode":"05","blindPositionReasonDesc":"Sun in window","time":"2016-03-06T18:30:24.935Z","altitude":0.030059333136498206,"azimuth":262.995658181589}
{"sunInWindow":false,"blindPosition":100,"blindPositionReasonCode":"02","blindPositionReasonDesc":"Sun below horizon","time":"2016-03-06T18:40:24.945Z","altitude":-1.8887389118866331,"azimuth":264.58194101656466}
```

With a +/- 45º offset I would expect the blind to “move” when the sun is between 135 and 225 however that’s clearly not what happening.
There was no “movement” between 08:10 and 17:40 which is precisely the time of the day where the sun is hitting that window (I suppose this can be due to Top and Bottom values but still, these values are not that far from reality)
Window start closing when the sun’s azimuth was > 254º which is outside the offset interval (135-225) with “Sun in Window” code but at this time there’s little to no sun light on that blind.
Not saying there’s a bug or anything like that, odds are it’s me missing something obvious

**Comment by alisdairjsmyth** [comment]
@jonferreira - I had difficulty reproducing your results so decided to put together a flow which simulates 6 March 2016 in your location.  You can import the flow into your Node-RED implementation using the appropriate menu option.

In this flow I define 4 blinds, each with the same properties except for the **channel** and **orientation**, and then inject **sunpos** messages which reflect the movement of the sun on that day.  I used your time, altitude and azimuth combinations, and augmented them with some additional to reflect the sun in the southern sky during the middle of the day.

You run the flow by manually invoking each step - Initialise and then each step in sequence.

With the offset of +/- 45º, each window has (almost) mutually exclusive ranges of azimuth that apply.  During the coarse of the day:
- At sunrise, all the blinds are activated.  Blinds 1,3,4 are not in the sun so move to the fully open position.  Blind 2 is in the sun, as because of the suns low position in the sky is initially closed.
- As the sun rises, Blind 2 progressively opens
- When the Sun passes through 135º, Blind 2 is not longer considered to be in the sun - Blind 3 is.  Though because of the sun's high altitude, Blind 3 remains fully open.
- When the Sun passes through 225º, control transfers to Blind 4.
- Then as the sun descends in the sky, Blind 4 progressively closes.
- At sunset all the blinds close.

[test.txt](https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller/files/162540/test.txt)

**Comment by jonferreira** [comment]
Fantastic work @alisdairjsmyth, thanks.

I don't know what to say though, it does work "as expected" with your test flow...I'm stumped.

I'm attaching my flow, maybe you can spot what I'm missing. In any case I'll keep monitoring it and see if I can figure out what's going on...

http://pastebin.com/haQYpp0B

**Comment by alisdairjsmyth** [comment]
I think you need the **channel** to be included in the message that you log to the file - otherwise you don't know the blind which is under control.  It is possible that when you observed the lowering of the blind as the sun set, those instructions likely related to the blind 1, the west blind.

**Comment by jonferreira** [comment]
I'm saving each blind log into a different file:

`newmsg.filename = "/root/vera_network/SunPositionBlind_" + msg.payload.channel + ".txt";`

that's not supposed to happen but I'll add the channel to the log messaged as well :)

**Comment by alisdairjsmyth** [comment]
I missed that point.

**Comment by jonferreira** [comment]
Hi @alisdairjsmyth ,
So after some testing I’ve two suggestions:

1)	There may be a bug in Winter mode where default Night Position is 0 instead of 100 – manually set it to 100 fixes it ofc

2)	Winter mode doesn’t have a “gradual” open/close. So while Blind A in Summer mode goes through all this different positions (0, 15, 30, 60, etc) in Winter mode the same blind is either fully opened or closed. I understand the logic behind it – if it’s to maximize light then fully opened is deffo the answer – but would be nice to have the option to behave similar as in Winter mode, i.e. gradually open/close the blind

**Comment by alisdairjsmyth** [comment]
v3.0.3 contains a fix for item 1.

**Comment by jonferreira** [comment]
great, will upgrade and test it, thanks

**Comment by alisdairjsmyth** [comment]
Regarding item 2 - "gradual open/close in Winter mode".
* Summer mode doesn't gradually open/close the window - it sets the position of the window to limit the extent direct light enters the room based on the parameters provided.  This may give the impression of a gradual shift in position - particularly if the blind can controlled with small increments - but it wasn't the intent.
* Blind movement is not instantaneous - in my own case the movement between fully open and fully closed positions takes circa 5 seconds.

Implementation of a "rate of change" mechanism to provide a gradual movement of the blind is not something I am considering.
