### ISSUE TITLE
Fix variable names in README.md

### ISSUE THREAD

**Issue by renne** [alisdairjsmyth/node-red-contrib-blindcontroller#33]
Variable names with whitespaces in [README.md](https://github.com/alisdairjsmyth/node-red-contrib-blindcontroller/blob/master/README.md) like "negative offset", "positive offset", "altitude threshold", "max open", "max closed", "temperature threshold", "temperature threshold position", "clouds threshold", "clouds threshold position", "night position" and "expiry period" cannot be used in ECMAScript. I assume it should be underscore.

Please fix README.md

**Comment by alisdairjsmyth** [comment]
There are two sections of the README.md. The first describes the parameters that can be set in the Information sidebar for the `Blind Controller` node.  These are labels and therefore not subject to ECMAScript naming constraints.

![image](https://user-images.githubusercontent.com/11627564/61374685-51cc6080-a8e0-11e9-95e7-6b0e758b64ab.png)

The second part describes the attribute names for the messages accepted by the nodes.  These attribute names need to conform to JSON standard.  There are several issues in this section that require correction:

- max open
- max closed
- night position
- expiry period

**Comment by alisdairjsmyth** [comment]
Fix in npm version 4.8.3
