### ISSUE TITLE
UV Threshold behaviour

### ISSUE THREAD

**Issue by Swiftnesses** [alisdairjsmyth/node-red-contrib-blindcontroller#35]
Hi,

I've recently updated from my fork (where I implemented UV threshold).

I'm a little confused with the logic, as of now I have the UV limit set to '3' and the position set to fully closed (default). Using winter mode (to maximise light), currently the blind keeps closing with status 'UV index below threshold', surely it should be open then, to maximise light (sun is in window right now)?

**Comment by Swiftnesses** [comment]
I should add, the current index is 1.

**Comment by benderl** [comment]
I think, the calculation in summer mode is also wrong. If uvindex is below the threshold, the blind gets closed. In the description of this setting, it is mentioned the other way round.
